import { ChallengeType, ChallengePeriod } from "@prisma/client"

export const PREDEFINED_CHALLENGES = [
    {
        title: "🌍 Explorateur de Genres",
        description: "Lisez 5 livres de genres différents",
        challengeType: "GENRE_DIVERSITY" as ChallengeType,
        target: 5,
        period: "ANYTIME" as ChallengePeriod,
        icon: "🌍",
        isPredefined: true,
    },
    {
        title: "📚 Marathon de Lecture",
        description: "Terminez 3 livres de plus de 500 pages",
        challengeType: "LONG_BOOKS" as ChallengeType,
        target: 3,
        period: "ANYTIME" as ChallengePeriod,
        icon: "📚",
        isPredefined: true,
    },
    {
        title: "📖 Lecteur Assidu",
        description: "Lisez 12 livres en un an",
        challengeType: "BOOK_COUNT" as ChallengeType,
        target: 12,
        period: "YEARLY" as ChallengePeriod,
        icon: "📖",
        isPredefined: true,
    },
    {
        title: "✍️ Diversité Littéraire",
        description: "Découvrez 5 auteurs différents",
        challengeType: "AUTHOR_DIVERSITY" as ChallengeType,
        target: 5,
        period: "ANYTIME" as ChallengePeriod,
        icon: "✍️",
        isPredefined: true,
    },
    {
        title: "💬 Critique Prolifique",
        description: "Rédigez 10 critiques de livres",
        challengeType: "REVIEW_COUNT" as ChallengeType,
        target: 10,
        period: "ANYTIME" as ChallengePeriod,
        icon: "💬",
        isPredefined: true,
    },
    {
        title: "🔥 Série de Feu",
        description: "Lisez pendant 7 jours consécutifs",
        challengeType: "READING_STREAK" as ChallengeType,
        target: 7,
        period: "ANYTIME" as ChallengePeriod,
        icon: "🔥",
        isPredefined: true,
    },
    {
        title: "📄 Dévoreur de Pages",
        description: "Lisez 10 000 pages au total",
        challengeType: "PAGE_COUNT" as ChallengeType,
        target: 10000,
        period: "YEARLY" as ChallengePeriod,
        icon: "📄",
        isPredefined: true,
    },
    // Nouveaux défis
    {
        title: "🐭 Rat de Bibliothèque",
        description: "Lisez 4 livres ce mois-ci",
        challengeType: "BOOK_COUNT" as ChallengeType,
        target: 4,
        period: "MONTHLY" as ChallengePeriod,
        icon: "🐭",
        isPredefined: true,
    },
    {
        title: "⚡ Week-end Lecture",
        description: "Lisez 1 livre cette semaine",
        challengeType: "BOOK_COUNT" as ChallengeType,
        target: 1,
        period: "WEEKLY" as ChallengePeriod,
        icon: "⚡",
        isPredefined: true,
    },
    {
        title: "🏛️ Collectionneur",
        description: "Atteignez une collection de 50 livres",
        challengeType: "COLLECTION_SIZE" as ChallengeType,
        target: 50,
        period: "ANYTIME" as ChallengePeriod,
        icon: "🏛️",
        isPredefined: true,
    },
    {
        title: "💡 Citations Inspirantes",
        description: "Sauvegardez 20 citations",
        challengeType: "QUOTE_COUNT" as ChallengeType,
        target: 20,
        period: "ANYTIME" as ChallengePeriod,
        icon: "💡",
        isPredefined: true,
    },
    {
        title: "🚀 Grand Voyageur",
        description: "Lisez 10 livres de genres différents",
        challengeType: "GENRE_DIVERSITY" as ChallengeType,
        target: 10,
        period: "ANYTIME" as ChallengePeriod,
        icon: "🚀",
        isPredefined: true,
    },
    {
        title: "🧱 Pavés de l'été",
        description: "Lisez 5 livres de plus de 500 pages",
        challengeType: "LONG_BOOKS" as ChallengeType,
        target: 5,
        period: "ANYTIME" as ChallengePeriod,
        icon: "🧱",
        isPredefined: true,
    },
    {
        title: "🌟 Découverte d'Auteurs",
        description: "Lisez 10 auteurs différents",
        challengeType: "AUTHOR_DIVERSITY" as ChallengeType,
        target: 10,
        period: "ANYTIME" as ChallengePeriod,
        icon: "🌟",
        isPredefined: true,
    },
    {
        title: "🏃 Marathonien des Pages",
        description: "Lisez 5 000 pages en un an",
        challengeType: "PAGE_COUNT" as ChallengeType,
        target: 5000,
        period: "YEARLY" as ChallengePeriod,
        icon: "🏃",
        isPredefined: true,
    },
    {
        title: "📝 Critique Expert",
        description: "Rédigez 25 critiques de livres",
        challengeType: "REVIEW_COUNT" as ChallengeType,
        target: 25,
        period: "ANYTIME" as ChallengePeriod,
        icon: "📝",
        isPredefined: true,
    },
    {
        title: "📅 Habitude Quotidienne",
        description: "Lisez 30 jours d'affilée",
        challengeType: "READING_STREAK" as ChallengeType,
        target: 30,
        period: "ANYTIME" as ChallengePeriod,
        icon: "📅",
        isPredefined: true,
    },
    {
        title: "🏰 Bibliothèque Royale",
        description: "Atteignez une collection de 100 livres",
        challengeType: "COLLECTION_SIZE" as ChallengeType,
        target: 100,
        period: "ANYTIME" as ChallengePeriod,
        icon: "🏰",
        isPredefined: true,
    },
    {
        title: "🏎️ Lecteur Rapide",
        description: "Lisez 2 livres cette semaine",
        challengeType: "BOOK_COUNT" as ChallengeType,
        target: 2,
        period: "WEEKLY" as ChallengePeriod,
        icon: "🏎️",
        isPredefined: true,
    },
    {
        title: "📅 Année Littéraire",
        description: "Lisez 24 livres en un an",
        challengeType: "BOOK_COUNT" as ChallengeType,
        target: 24,
        period: "YEARLY" as ChallengePeriod,
        icon: "📅",
        isPredefined: true,
    },
    {
        title: "🌌 Explorateur de Mondes",
        description: "Lisez 15 livres de genres différents",
        challengeType: "GENRE_DIVERSITY" as ChallengeType,
        target: 15,
        period: "ANYTIME" as ChallengePeriod,
        icon: "🌌",
        isPredefined: true,
    },
    {
        title: "🐉 Amateur de Sagas",
        description: "Lisez 10 livres de plus de 500 pages",
        challengeType: "LONG_BOOKS" as ChallengeType,
        target: 10,
        period: "ANYTIME" as ChallengePeriod,
        icon: "🐉",
        isPredefined: true,
    },
    {
        title: "🗣️ Voix Multiples",
        description: "Lisez 20 auteurs différents",
        challengeType: "AUTHOR_DIVERSITY" as ChallengeType,
        target: 20,
        period: "ANYTIME" as ChallengePeriod,
        icon: "🗣️",
        isPredefined: true,
    },
    {
        title: "✒️ Plume Aiguisée",
        description: "Rédigez 50 critiques de livres",
        challengeType: "REVIEW_COUNT" as ChallengeType,
        target: 50,
        period: "ANYTIME" as ChallengePeriod,
        icon: "✒️",
        isPredefined: true,
    },
    {
        title: "❤️ Passionné",
        description: "Lisez 100 jours d'affilée",
        challengeType: "READING_STREAK" as ChallengeType,
        target: 100,
        period: "ANYTIME" as ChallengePeriod,
        icon: "❤️",
        isPredefined: true,
    },
    {
        title: "🏔️ Montagne de Pages",
        description: "Lisez 20 000 pages en un an",
        challengeType: "PAGE_COUNT" as ChallengeType,
        target: 20000,
        period: "YEARLY" as ChallengePeriod,
        icon: "🏔️",
        isPredefined: true,
    },
    {
        title: "👑 Légende Littéraire",
        description: "Lisez 52 livres en un an",
        challengeType: "BOOK_COUNT" as ChallengeType,
        target: 52,
        period: "YEARLY" as ChallengePeriod,
        icon: "👑",
        isPredefined: true,
    },
]
