import { ChallengeType, ChallengePeriod } from "@prisma/client"

export const PREDEFINED_CHALLENGES = [
    {
        title: "🌍 Explorateur de Genres",
        description: "Lisez 5 livres de genres différents",
        challengeType: "GENRE_DIVERSITY" as ChallengeType,
        target: 5,
        period: "ANYTIME" as ChallengePeriod,
        icon: "🌍",
        isPredefined: true,
    },
    {
        title: "📚 Marathon de Lecture",
        description: "Terminez 3 livres de plus de 500 pages",
        challengeType: "LONG_BOOKS" as ChallengeType,
        target: 3,
        period: "ANYTIME" as ChallengePeriod,
        icon: "📚",
        isPredefined: true,
    },
    {
        title: "📖 Lecteur Assidu",
        description: "Lisez 12 livres en un an",
        challengeType: "BOOK_COUNT" as ChallengeType,
        target: 12,
        period: "YEARLY" as ChallengePeriod,
        icon: "📖",
        isPredefined: true,
    },
    {
        title: "✍️ Diversité Littéraire",
        description: "Découvrez 5 auteurs différents",
        challengeType: "AUTHOR_DIVERSITY" as ChallengeType,
        target: 5,
        period: "ANYTIME" as ChallengePeriod,
        icon: "✍️",
        isPredefined: true,
    },
    {
        title: "💬 Critique Prolifique",
        description: "Rédigez 10 critiques de livres",
        challengeType: "REVIEW_COUNT" as ChallengeType,
        target: 10,
        period: "ANYTIME" as ChallengePeriod,
        icon: "💬",
        isPredefined: true,
    },
    {
        title: "🔥 Série de Feu",
        description: "Lisez pendant 7 jours consécutifs",
        challengeType: "READING_STREAK" as ChallengeType,
        target: 7,
        period: "ANYTIME" as ChallengePeriod,
        icon: "🔥",
        isPredefined: true,
    },
    {
        title: "📄 Dévoreur de Pages",
        description: "Lisez 10 000 pages au total",
        challengeType: "PAGE_COUNT" as ChallengeType,
        target: 10000,
        period: "YEARLY" as ChallengePeriod,
        icon: "📄",
        isPredefined: true,
    },
]
